#服务名称
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activity?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      filter:
        stat:
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
    connection-init-sqls: SET NAMES utf8mb4
    initialSize: 3
    maxActive: 10
    maxWait: 30000
    minEvictableIdleTimeMillis: 300000
    minIdle: 3
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    validationQuery: SELECT 1 FROM DUAL

  mail:
    host: smtp.163.com
    username: snowingximen@163.com
    password: Snowing123
    protocol: smtp
    properties.mail.smtp.auth: true
#    properties.mail.smtp.port: 994
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: snowingximen@163.com

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

app:
  mail:
    subject: welcome to PCCW
    to: snowingximen@163.com

